create TABLE IF NOT EXISTS contract (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PO VARCHAR,
    clientName VARCHAR,
    nameEPU VARCHAR,
    addressEPU VARCHAR,
    contractMethod VARCHAR,
    contractNumber VARCHAR,
    contractDate DATE,
    voltage DOUBLE,
    reliabilityCategory INT,
    powerMax DOUBLE,
    powerNew DOUBLE,
    contractCost DOUBLE,
    deadline DOUBLE,
    nameObject VARCHAR(500),
    status VARCHAR,
    actDate DATE
);